import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Footer from '../components/Footer';
import Header from '../components/Header';
import LoginModal from '../components/loginModal/LoginModal';
import PasswordForgotten from '../components/passwordForgotten/PasswordForgotten';
import SignUpModal from '../components/signUpModal/SignUpModal';
import styles from './index.module.css';

export default function Home() {
 const [isOpen, setIsOpen] = useState(false);
 const [signUpModalIsOpen, setSignUpModalIsOpen] = useState(false);
 const [passwordForgottenModal, setPasswordForgottenModal] = useState(false);
 const router = useRouter();

 const deleteLoginParameter = () => {
  const currentUrl = new URL(window.location.href);
  currentUrl.searchParams.delete('login');
  history.pushState({}, '', currentUrl.href);
 };

 useEffect(() => {
  const { login } = router.query;

  if (login) {
   deleteLoginParameter();
   setIsOpen(true);
  }
 }, [router.query]);

 return (
  <>
   <Head>
    <title>Create Next App</title>
    <meta name='description' content='Generated by create next app' />
    <meta name='viewport' content='width=device-width, initial-scale=1' />
    <link rel='icon' href='/favicon.ico' />
   </Head>
   <div className={styles.container}>
    <Header setIsOpen={setIsOpen} />
    <Footer author={'Luciano Polo'} />
    {isOpen && (
     <LoginModal
      setIsOpen={setIsOpen}
      setSignUpModalIsOpen={setSignUpModalIsOpen}
      setPasswordForgottenModal={setPasswordForgottenModal}
     />
    )}
    {signUpModalIsOpen && (
     <SignUpModal
      setSignUpModalIsOpen={setSignUpModalIsOpen}
      setIsOpen={setIsOpen}
     />
    )}

    {passwordForgottenModal && (
     <PasswordForgotten setPasswordForgottenModal={setPasswordForgottenModal} />
    )}
   </div>
  </>
 );
}

Home.getInitialProps = async (context) => {
 // context.query contiene las propiedades de la URL
 return { login: context.query.login };
};
