import Head from 'next/head';
import { useState } from 'react';
import { Footer } from '../components/Footer';
import { Header } from '../components/Header';
import LoginModal from '../components/loginModal/LoginModal';
import SignUpModal from '../components/signUpModal/SignUpModal';

export default function Home() {
 const [profile, setProfile] = useState({});
 const [isOpen, setIsOpen] = useState(false);
 const [signUpModalIsOpen, setSignUpModalIsOpen] = useState(false);

 return (
  <>
   <Head>
    <title>Create Next App</title>
    <meta name='description' content='Generated by create next app' />
    <meta name='viewport' content='width=device-width, initial-scale=1' />
    <link rel='icon' href='/favicon.ico' />
   </Head>
   <div>
    <Header setIsOpen={setIsOpen} profile={profile} setProfile={setProfile} />
    <Footer author={'Luciano Polo'} />
    {isOpen && (
     <LoginModal
      setIsOpen={setIsOpen}
      setProfile={setProfile}
      setSignUpModalIsOpen={setSignUpModalIsOpen}
     />
    )}
    {signUpModalIsOpen && (
     <SignUpModal
      setSignUpModalIsOpen={setSignUpModalIsOpen}
      setIsOpen={setIsOpen}
     />
    )}
   </div>
  </>
 );
}
